---
title: "Detailed info for LAU2boundaries4spain"
author: "Francisco Goerlich & Pedro J. Perez"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Detailed info for LAU2boundaries4spain}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


## Visión de conjunto.

El objetivo de este repositorio es ofrecer los contornos de los términos municipales españoles ajustados a los municipios existentes a 1 de enero de cada año desde 2002, de forma que cuadren exactamente con el Padrón de dicho año. Los contornos a fecha de 1 de enero de 2002 son consistentes con los existentes en el censo de 2001, con fecha de referencia 1 de noviembre de dicho año. La información ofrecida ha ido elaborándose durante bastante tiempo a partir de diversos trabajos (Goerlich, Mas, Azagra y Chorén 2006, 2007; Goerlich, Ruiz, Chorén y Albert 2015; Reig, Goerlich y Cantarino 2016).

Creemos que dicha base de datos es útil por varias razones. El [Instituto Geográfico Nacional](http://www.ign.es/web/ign/portal) (IGN) ofrece, a través del [Centro de Descargas](http://centrodedescargas.cnig.es/CentroDescargas/index.jsp) del Centro Nacional de Información Geográfica (CNIG), los recintos municipales --también los provinciales y autonómicos-- dentro de la Base de Datos de Líneas de Límite Municipal en la **Información Geográfica de Referencia**, sin embargo estas bases de datos son de actualización continua, de forma que lo que se dispone son los municipios "en el momento actual", y no existe un histórico que puede ser de utilidad por muchas razones. Así pues, hasta donde nosotros conocemos, no se dispone, por ejemplo, de una capa vectorial de los polígonos municipales del año 2006, o de la de los municipios correspondientes al censo de 2001. Esta información es necesaria si queremos combinar la información geográfica con la información estadística municipal histórica procedente, por ejemplo, del [Instituto Nacional de Estadística](http://www.ine.es/) (INE).

Este repositorio pretende cubrir esa laguna que, de momento, no ha sido satisfecha por las instituciones oficiales. El repositorio está disponible como un _package_ de _R_ alojado en _Github_: <https://github.com/perezp44/LAU2boundaries4spain>.

Información más detallada del proceso seguido para la construcción de los diferentes ficheros de lindes puede encontrase en una de las *vignettes* del *package*, concretamente [aquí](https://htmlpreview.github.io/?https://github.com/perezp44/LAU2boundaries4spain/blob/master/inst/doc/detailed-info-lau2boundaries4spain.html)


## ¿Como se organiza y trata la información original?

El procedimiento por el cual organiza y elabora la información disponible es el siguiente.

Dado el carácter continuo de la información proporcionada por el CNIG los contornos históricos se reconstruyeron a partir de diversas descargas de la Base de Datos de Líneas de Límite del [Centro de Descargas](http://centrodedescargas.cnig.es/CentroDescargas/index.jsp)[^1], la recopilación de las alteraciones municipales desde 2002[^2] y diversas operaciones simples en el contexto de los Sistemas de Información Geográfica (SIG), como la generalización de polígonos, el combinado o fusionado de capas y la edición de ciertos lindes.

El proceso implica además ciertas manipulaciones para ofrecer capas homogéneas para el periodo 2001 a 2020.

- Canarias suele distribuirse, aunque no siempre, como una capa separada en sistema de referencia geodésico WGS84, por lo que hubo que transformarlo de sistema de referencia y fusionarlo con el fichero de la península y Baleares[^3].

- Las capas de lindes municipales incluyen los polígonos que no pertenecen a municipios, los llamados condominios, cuya codificación y nomenclatura ha cambiado considerablemente a lo largo del tiempo. Estos se han homogeneizado de acuerdo con la última práctica del IGN.[^4] No es seguro que esta codificación se mantenga en el tiempo, dado lo peculiar de estos territorios[^5].

- Se extrajeron, en algunos casos, errores del propio IGN en la base de datos descargada, como alguna duplicidad, polígonos multiparte con código único, o códigos intercambiados en la tabla de atributos.

- Finalmente, y dado que hasta fechas muy recientes, el IGN no ofrecía polígono para el municipio de Fago, 22106, solo un polígono para dos municipios, Fago, 22106, y Ansó, 22028, por no existir acta de deslinde entre ambos municipios en el Registro Central de Cartografía, hubo que recuperar y editar el polígono de este municipio a partir de bases de datos anteriores. Más recientemente el IGN si incluye a dicho municipio en la Base de Datos de Líneas de Límite, siendo consistente con el recuperado de bases anteriores.

Finalmente, tras estos procesos, se obtuvieron ficheros de contornos municipales, y un registro por recinto --municipio o condominio-- en la tabla de atributos. Los condominios son 84 hasta 2018 y 81 para 2019 y 2020, y los municipios los existentes a fecha de 1 de enero de cada año.

## ¿Qué información se ofrece?

La información se ofrece en el formato del paquete [`sf`](https://cran.r-project.org/web/packages/sf/index.html) de _R_ y sistema de referencia geodésico europeo, ETRS89 en coordenadas geográficas, es decir sin proyección.

Tal y como se indica abajo se ofrece un fichero de polígonos municipales por año, y para Provincias y Comunidades Autónomas (CCAA) solo uno, el correspondiente a la descarga más reciente[^6]. Si lo que se desea es disponer de una capa de Provincias o CCAA que sea plenamente consistente con los municipios de un año concreto para hacer cálculos geográficos se recomienda que dicha layer sea obtenida por generalización del fichero de municipios correspondiente. La razón es que entre descargas se suelen producir alteraciones en los lindes de provincia, CCAA, frontera o de costa, por ejemplo, aunque solo sea por redefinición geométrica. De esta forma se asegura que la información de Provincias y Comunidades Autónomas es totalmente compatible con la de los ficheros de municipios de ese año.


## Información finalmente ofrecida y decisiones tomadas.

* Sistema de referencia geodésico: ETRS89 en coordenadas geográficas, sin proyección.

* Contornos municipales para los años 2002-2020 

* Contornos municipales para provincias y otra para CCAA (procedente de la descarga más reciente).

* Tablas de atributos:

    - INECodMuni: Código INE para el municipio (5 digitos)

    - NombreMuni: Nombre del municipio (o condominio)

    - INECodProv: Código provincial

    - NombreProv: Nombre de la provincia

    - INECodCCAA: Código de la C.A.

    - NombreCCAA: Nombre de la C.A.

* Convención sobre Ceuta y Melilla: Aparecen separadas en la capa provincias, pero juntas, con el código 18, en la de CCAA.

* Codificación de los condominios: La codificación de los condominios ha cambiado en el tiempo y se ha mantenido la codificación y nomenclatura más reciente por parte del IGN.

* La capa de municipios de 2002 es compatible con los municipios del censo de 2001, 8108 municipios, y las capas de 2011 y 2012 son compatibles con los municipios del censo de 2011, 8116 municipios.

## Referencias

* **Goerlich, F. J. (2012)**: Estimaciones de la Población Actual (ePOBa) a nivel Municipal –Discrepancias Censo-Padrón a pequeña escala–. Boletín de la A.G.E. Vol.-58, 1er cuatrimestre, pp.-83-104.

* **Goerlich, F. J. y Cantarino, I. (2012)**: Una grid de densidad de población para España. Economía y Sociedad. Informe Técnico. Fundación BBVA. Bilbao.

* **Goerlich, F. J., Mas, M., Azagra, J. y Chorén, P. (2006)**: La Localización de la Población Española sobre el Territorio. Un Siglo de Cambios. Un estudio basado en series temporales homogéneas (1900-2001). Fundación BBVA. Bilbao.

* **Goerlich, F. J., Mas, M., Azagra, J. y Chorén, P. (2007)** : Actividad y Territorio. Un Siglo de Cambios. Fundación BBVA. Bilbao.

* **Goerlich, F. J., Ruiz, F., Chorén, P. y Albert, C. (2015)**: Cambios en la Estructura y Localización de la Población. Una visión de largo plazo (1842-2011). Fundación BBVA. Bilbao.

* **Reig, E.; Goerlich, F. J. y Cantarino, I. (2016)**: Delimitación de áreas rurales y urbanas a nivel local. Demografía, coberturas del suelo y accesibilidad. Economía y Sociedad. Informe Técnico. Fundación BBVA. Bilbao.


[^1]: En concreto se efectuaron descargas en mayo de 2011, febrero de 2013, junio de 2016 y febrero de 2020. El formato original de descarga es shape de ESRI, y el tratamiento de los ficheros se hizo en ArcGIS y R.

[^2]: Las alteraciones municipales pueden encontrase en el [INE](http://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736177031&menu=ultiDatos&idp=1254734710990) o para todos los censos en Goerlich, Ruiz, Chorén y Albert (2015).

[^3]: Para una introducción a los sistemas de referencia geodésicos para no especialistas puede verse el apéndice A.3 de Goerlich y Cantarino (2012).

[^4]: Así por ejemplo, en la última actualización desaparecieron 3 condominios que fueron absorbidos por dos municipios. Se recomienda, en cualquier caso la consulta de la tabla de Condominios del Nomneclator de Municipios y Entidades de Población del IGN.

[^5]: Sobre los condominios véase el apéndice de Goerlich, Ruiz, Chorén y Albert (2015).

[^6]: Dichas capas se obtuvieron por generalización de la capa de contornos municipales, y no se tomaron directamente de la Base de Datos de Líneas de Límite del CNIG.


