---
title: "Detailed info for LAU2boundaries4spain"
author: "Francisco Goerlich & Pedro J. Perez"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Detailed info for LAU2boundaries4spain}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Visión de conjunto.

El objetivo de este repositorio es ofrecer los contornos de los términos municipales españoles en un contexto histórico, y ajustados a los municipios existentes a 1 de enero de cada año, de forma que cuadren exáctamente con el Padrón de dicho año. La información ofrecida ha ido elaborandose durante bastante tiempo a partir de diversos trabajos (Goerlich, Mas, Azagra y Chorén 2006, 2007; Goerlich, Ruiz, Chorén y Albert 2015; Reig, Goerlich y Cantarino 2016).

Creemos que dicha base de datos es útil por varias razones. El [Instituto Geográfico Nacional](http://www.ign.es/web/ign/portal) (IGN) ofrece, a través del [Centro de Descargas](http://centrodedescargas.cnig.es/CentroDescargas/index.jsp) del Centro Nacional de Información Geográfica (CNIG), los recintos municipales (también los provinciales y autonómicos) dentro de la Base de Datos de Líneas de Límite Municipal en la **Información Geográfica de Referencia**, sin embargo estas bases de datos son de actualización continua, de forma que lo que se dispone son los municipios "en el momento actual", y no existe un histórico que puede ser de utilidad por muchas razones. Así pues, hasta donde nosostros conocemos, no se dispone, por ejemplo, de una capa vectorial de los polígonos municipales del año 2006, o de la de los municipios correspondientes al censo de 2001, por ejemplo. Esta información es necesaria si queremos mezclar la información geográfica con la información estadística municipal histórica procedente, por ejemplo, del [Instituto Nacional de Estadística](http://www.ine.es/) (INE).

Este repositorio pretende cubrir esa laguna que, de momento, no ha sido satisfecha por las instituciones oficiales.

El repositorio está disponible como un package de R en GitHub con el nombre `LAU2boundaries4spain` en: <https://github.com/perezp44/LAU2boundaries4spain>.


## ¿Como se organiza y trata la información original?

El procedimiento por el cual organiza y elabora la información disponible es el siguiente.

A partir de una descarga inicial de la Base de Datos de Líneas de Límite del [Centro de Descargas](http://centrodedescargas.cnig.es/CentroDescargas/index.jsp) en Mayo de 2011 se obtuvieron los polígonos de los municipios correspondientes a fecha de 1 de enero de 2011, 8116 municipios. Para ello el fichero original del IGN tuvo que ser depurado en varios aspectos.

El fichero que contenía los recintos municipales de Canarias estaba separado del resto (actualmente también es así, pero no siempre el IGN ha adoptado esta práctica), por lo que todos los municipios se pusieron en una única capa manteniendo el sistema de referencia geodésico de los municipios de la Península (ETRS89) sin proyección [^1]. 

Se extrajeron los polígonos que no pertenecen a municipios, los llamados condominios, cuya codificación en aquel momento era inexistente. Los condominios se exportaron a otro fichero y se obtuvo un registro en la tabla de atributos por cada condominio mediante generalización (disolve)[^2].


Hubo que arreglar algunas imprecisiones como: 

  - El polígono de Suances, 39085, estaba duplicado por lo que se eliminó la duplicidad. 

  - Los municipios de Urretxu, 20080, y Zumarraga, 20077, estaban intercambiados en la tabla de atributos, lo que se corrigió.

  - En aquel momento, y hasta fechas muy recientes, el IGN no ofrecía polígono para el municipio de Fago, 22106, solo un polígono para dos municipios, Fago, 22106, y Ansó, 22028, por no existir acta de deslinde entre ambos municipios en el Registro Central de Cartografía. Dado que el objetivo era asignar estadísticas a polígonos municipales se obtuvo el polígono de Fago, 22106, de una base de datos anterior al [Centro de Descargas](http://centrodedescargas.cnig.es/CentroDescargas/index.jsp) y procedente del propio IGN. Dicha base de datos se obtuvo mediante WFS en formato gml.

Finalmente, tras este proceso, se dispuso de un fichero con los contornos municipales y un registro por municipio en la tabla de atributos con fecha de referencia 1 de enero de 2011, 8116 municipios y 84 condominios.

Puesto que entre 2002 y 2011 solo se han producido 8 segregaciones municipales, rastreando las segregaciones y mediante generalización (disolve) se obtuvieron los ficheros de contornos municipales a fecha 1 de enero de cada año entre 2002 y 2011. El fichero de 2002 coincide con los municipios existentes en el censo de 2001, 8108, con fecha de referencia 1 de noviembre [^3].



Se realizó un proceso similar para otras dos descargas; una en Febrero 2013 y otra el 30/06/2016. 

Esto proporciona, inicialmente, una serie de contornos municipales de 2002 a 2016 (con referencia 1 de enero), pero como a lo largo de 2016 solo se produce una fusión de 2 municipios obtenemos por generalización(disolve) de ellos las geometrías para 2017, y como a lo largo de 2017 no se produce ninguna alteración municipal, disponemos finalmente de una serie de contornos municipales de 2002 a 2018 [^4].



## ¿Qué información se ofrece?

La información se ofrece en el formato del paquete [`sf`](https://cran.r-project.org/web/packages/sf/index.html) de R y sistema de referencia geodésico ETRS89 sin proyección. Esto sigue la convención del IGN. 

Tal y como se indica abajo se ofrece un fichero de polígonos municipales por año, y para provincias y Comunidades Autónomas solo uno, el de la descarga de 2016. . No obstante, si lo que se desea es disponer de una *layer* de Provincias o CCAA que sea consistente con los municipios de un año concreto para hacer cálculos geográficos se recomienda que dicha layer sea obtenida por generalización del fichero de municipios correspondiente. La razón es que entre descargas se pueden haber producido alteraciones en los lindes de provincia, CCAA, frontera o de costa, por ejemplo, aunque solo sea por redefinición geométrica. De esta forma se asegura que la información de provincias y Comunidades Autónomas es totalmente compatible con la de los ficheros de municipios de esa año.



## Información finalmente ofrecida y decisiones tomadas.

* Sistema de referencia geodésico: ETRS89 en coordenadas geográficas, sin proyección.

* Contornos municipales para los años 2002-2018 

* Contornos municipales para provincias y otra para CCAA (que procede de la descarga del 30/6/2016).

* Tablas de atributos:

    - INECodMuni: Código INE para el municipio (5 digitos)

    -  NombreMuni: Nombre del municipio (o condominio)

    - INECodProv: Código provincial

    - NombreProv: Nombre de la provincia

    - INECodCCAA: Código de la C.A.

    - NombreCCAA: Nombre de la C.A.

* Convención sobre Ceuta y Melilla: Aparecen separadas en las _layers_ de municipio y provincias, pero juntas, con el código 18, en la de CCAA.

* Codificación de los condominios: La codificación de los condominios ha cambiado en el tiempo y hubo que arreglarla ex-profeso para esta base de datos. No se garantiza que no cambie en el futuro. En concreto la codificación era consistente en las Bases 2013 y 2016: 5 dígitos empezando por 53 y 3 dígitos correlativos empezando en 000 y acabando en 084 (el código 030 no existe). Obsérvese que los dos primeros dígitos no son los de la provincia, aunque se dispone en la base de datos original de la identificación provincial de cada condominio. En la Base 2011 la codificación, y también los nombres, era diferente: 5 dígitos, los dos primeros los de la provincia, el tercero 8 y los otros dos correlativos dentro de cada provincia empezando 01. Los nombres eran también diferentes. Para ofrecer la misma codificación y nombre de los condominios a lo largo de todas las _layers_ municipales se procedió a reconvertir los códigos y nombres de los condominios de la Base 2011 a los de la Base 2013. Inicialmente en la Base 2011 habían 83 condominios y en las Bases 2013 y 2016 habían 84. En el proceso de recodificación se observó que la razón de la discrepancia era que el código 09821 era multiparte, 2 polígonos, y estos tenían códigos diferentes en la Base 2013: 53039 y 53040. Esto se arregló en ArcGIS con _SinglepartToMultipart_ y luego con _disolve_, ya que hay otro condominio con 3 polígonos y código único: 53015/09827, pero esto no ha cambiado entre bases. De esta forma los condominios son siempre los mismos, 84, y tienen la misma codificación y el mismo nombre.


* La *layer* de municipios de 2002 es compatible con los municipios del censo de 2001, 8108 municipios, y las **layers** de 2011 y 2012 son compatibles con los municipios de 2011, 8116 municipios.


* No se ofrecen superficies. Sobre el cálculo de superficies puede verse apéndice A.3 de Goerlich y Cantarino (2012).

## Referencias

* **Goerlich, F. J. (2012)**: Estimaciones de la Población Actual (ePOBa) a nivel Municipal –Discrepancias Censo-Padrón a pequeña escala–. Boletín de la A.G.E. Vol.-58, 1er cuatrimestre, pp.-83-104.

* **Goerlich, F. J. y Cantarino, I. (2012)**: Una grid de densidad de población para España. Economía y Sociedad. Informe Técnico. Fundación BBVA. Bilbao.

* **Goerlich, F. J., Mas, M., Azagra, J. y Chorén, P. (2006)**: La Localización de la Población Española sobre el Territorio. Un Siglo de Cambios. Un estudio basado en series temporales homogéneas (1900-2001). Fundación BBVA. Bilbao.

* **Goerlich, F. J., Mas, M., Azagra, J. y Chorén, P. (2007)** : Actividad y Territorio. Un Siglo de Cambios. Fundación BBVA. Bilbao.

* **Goerlich, F. J., Ruiz, F., Chorén, P. y Albert, C. (2015)**: Cambios en la Estructura y Localización de la Población. Una visión de largo plazo (1842-2011). Fundación BBVA. Bilbao.

* **Reig, E.; Goerlich, F. J. y Cantarino, I. (2016)**: Delimitación de áreas rurales y urbanas a nivel local. Demografía, coberturas del suelo y accesibilidad. Economía y Sociedad. Informe Técnico. Fundación BBVA. Bilbao.




[^1]: Para una introducción a los sistemas de referencia geodésicos para no especialistas puede verse el apéndice A.3 de Goerlich y Cantarino (2012).

[^2]: Sobre los condominios véase el apéndice de Goerlich, Ruiz, Chorén y Albert (2015).

[^3]: Las alteraciones municipales pueden encontrase en el [INE](http://www.ine.es/dyngs/INEbase/es/operacion.htm?c=Estadistica_C&cid=1254736177031&menu=ultiDatos&idp=1254734710990) o para todos los censos en Goerlich, Ruiz, Chorén y Albert (2015).

[^4]: El formato original de descarga es _shape_ de ESRI, y el tratamiento de los ficheros se hizo en ArcGIS.

